export enum PlatformId {
  Unicode = 0,
  Macintosh = 1,
  ISO = 2,
  Windows = 3,
  Custom = 4,
}

export enum NameId {
  CopyrightNotice = 0,
  FontFamilyName = 1,
  FontSubfamilyName = 2,
  UniqueFontIdentifier = 3,
  FullFontName = 4,
  VersionString = 5,
  PostScriptName = 6,
  Trademark = 7,
  Manufacturer = 8,
  Designer = 9,
  Description = 10,
  VendorUrl = 11,
  DesignerUrl = 12,
  LicenseDescription = 13,
  LicenseUrl = 14,
  TypographicFamilyName = 16,
  TypographicSubfamilyName = 17,
  CompatibleFull = 18,
  SampleText = 19,
  PostScriptCidFindfontName = 20,
  WwsFamilyName = 21,
  WwsSubfamilyName = 22,
  LightBackgroundPalette = 23,
  DarkBackgroundPalette = 24,
  VariationsPostScriptNamePrefix = 25,
}
